<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>L2TrackerCompanion.Parsing</RootNamespace>
    <AssemblyName>L2TrackerCompanion.Parsing</AssemblyName>
  </PropertyGroup>

</Project>
